//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishStock
    {
        public int ID_FishStock { get; set; }
        public int ActiveID { get; set; }
        public int Quantity { get; set; }
        public string Pond { get; set; }
    
        public virtual Active Active { get; set; }
    }
}
