//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishingResults
    {
        public int ID_FishingResult { get; set; }
        public int RibalkaID { get; set; }
        public int ActiveID { get; set; }
        public int QuantityCaught { get; set; }
    
        public virtual Active Active { get; set; }
        public virtual Ribalka Ribalka { get; set; }
    }
}
