//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrders
    {
        public int ID_SalesOrder { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int ActiveID { get; set; }
        public int Quantity { get; set; }
        public int UserID { get; set; }
        public decimal TotalPrice { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual Active Active { get; set; }
        public virtual Users Users { get; set; }
    }
}
